### ISSUE TITLE
Errors when using special characters

### ISSUE THREAD

**Issue by alexjp** [livehelpnow/tds_ecto#11]
Hi,

When i have data on the ms sql database that uses special languages like " ç ã õ ", causes this error:

```
no function clause matching in Poison.Encoder.BitString.chunk_size/3

```

in

86  defp escape(string, mode) do
87    size = chunk_size(string, mode, 0)
88    <<chunk :: binary-size(size), rest :: binary>> = string
89    [chunk | escape(rest, mode)]
90  end

and console output:

*\* (exit) an exception was raised:
    *\* (FunctionClauseError) no function clause matching in Poison.Encoder.BitString.chunk_size/3
        (poison) lib/poison/encoder.ex:92: Poison.Encoder.BitString.chunk_size(<<231, 227, 111, 32, 68, 83, 76>>, nil, 9)
        (poison) lib/poison/encoder.ex:87: Poison.Encoder.BitString.escape/2
        (poison) lib/poison/encoder.ex:49: Poison.Encoder.BitString.encode/2
        (poison) lib/poison/encoder.ex:156: anonymous fn/4 in Poison.Encoder.Map.encode/2
        (stdlib) lists.erl:1261: :lists.foldl/3
        (poison) lib/poison/encoder.ex:157: Poison.Encoder.Map.encode/2
        (poison) lib/poison/encoder.ex:156: anonymous fn/4 in Poison.Encoder.Map.encode/2
        (stdlib) lists.erl:1261: :lists.foldl/3

I posted this here, not poison, because using the same data by json webservices or postgresql, does not seem to trigger this problem.

**Comment by mobileoverlord** [comment]
I might need a little more information here. Is this using the new map type in ecto 0.12.1?

**Comment by alexjp** [comment]
well, i can post my mix.lock :

```
%{"cowboy": {:hex, :cowboy, "1.0.0"},
  "cowlib": {:hex, :cowlib, "1.0.1"},
  "decimal": {:hex, :decimal, "1.1.0"},
  "ecto": {:hex, :ecto, "0.12.1"},
  "fs": {:hex, :fs, "0.9.2"},
  "hackney": {:hex, :hackney, "1.1.0"},
  "httpoison": {:hex, :httpoison, "0.7.0"},
  "idna": {:hex, :idna, "1.0.2"},
  "jsonapi": {:git, "git://github.com/jeregrine/jsonapi.git", "9877baf7f1c163640f5b44d2bcbe7a70c0dfb0e2", []},
  "phoenix": {:hex, :phoenix, "0.13.1"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "0.5.0"},
  "phoenix_html": {:hex, :phoenix_html, "1.2.1"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "0.4.1"},
  "plug": {:hex, :plug, "0.13.0"},
  "plug_cors": {:hex, :plug_cors, "0.7.3"},
  "poison": {:hex, :poison, "1.4.0"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.8.4"},
  "ranch": {:hex, :ranch, "1.0.0"},
  "ssl_verify_hostname": {:hex, :ssl_verify_hostname, "1.0.5"},
  "tds": {:hex, :tds, "0.2.8"},
  "tds_ecto": {:git, "git://github.com/livehelpnow/tds_ecto.git", "3508d28a02d711bc9f79535fd2f1354a59850449", []},
  "timex": {:hex, :timex, "0.15.0"},
  "tzdata": {:hex, :tzdata, "0.1.6"}}
```

**Comment by mobileoverlord** [comment]
Can you configure your logger to go a little deeper? I want to try to see where you are failing in the library. please add this to your config

```
config :logger, :console,
  truncate: 100_000
```

**Comment by mobileoverlord** [comment]
additionally there was a short period of time where we were defining the `:map` type as `text` instead of `nvarchar(max)` can you  please check the schema of the db and let me know what the column data type is set to?

**Comment by alexjp** [comment]
well, the column data type is varchar

**Comment by alexjp** [comment]
the text in question is "Demonstração".

If i remove the row with this text, it works

**Comment by mobileoverlord** [comment]
Ah, okay, so this is because these characters are in the windows 1252 code page and is used for char and varchar fields. Sigh, this has been a long time coming... I've been putting off having to support this deprecated windows specific code page casting to and from unicode. I am a believer in char and varchar being old field types and that these field types should be converted to nvarchar.

There are some examples in other TDS drivers for other langs like go and python which had manually implemented the 1252 code page for these column types and if you are feeling adventurous, we would certainly appreciate a PR for it. Alternatively, you could just convert these columns to nvarchar. Unicode will love you for it :)

**Comment by alexjp** [comment]
I completly understand ! :) unfortunatly i am developing against an closed source ERP system.
I will try to find a way around.
I might feel a adventurous in the future, but i am still pretty much learning elixir.

( by the way, an example like this : https://github.com/denisenkom/go-mssqldb/blob/master/cp1252.go ? )

**Comment by alexjp** [comment]
Also, completly right !!

Doing a CAST("varchar column" AS NVARCHAR) completly fixes it

**Comment by mobileoverlord** [comment]
That will work out well. I'll submit this as an open issue and close this one out for now and we can hope someone will pickup the call to adventure :)
