### ISSUE TITLE
Connect to named instance

### ISSUE THREAD

**Issue by Tica2** [livehelpnow/tds_ecto#17]
For named instance that alocate dinamic port is good to have conf option.

This is also issues for:
https://github.com/livehelpnow/tds

**Comment by Tica2** [comment]
is working with 
instance: "instancename"
in config/config.exs

If named instance alocate dinamic port (like 49xxx) be careful with the firewall.

**Comment by mobileoverlord** [comment]
@Tica2 You are right, if you add instance: "my_instance_name" it will tell the underlying Tds driver to make a UDP call to the SQL Server Browser Service at the hostname you provided. This returns a list of running instances where we will do a match for instance name and then internally make a call to connect with the port that was returned by the server.

This is used for situations where instances are set to use a dynamic port. If you have your instance set on a static port, you can omit the instance: key in favor of port: <my_port_number> where <my_port_number> would be the port number of your static assigned instance.

example

``` elixir
config :my_app, Repo,
  database: "ecto_simple",
  username: "mssql",
  password: "mssql",
  hostname: "localhost",
  port: 5387
```

Let me know if you are experiencing any additional issues with this.

Thanks!

**Comment by Tica2** [comment]
Is working fine! 
I think is good to add this option on README.md/docs be more clear.
I can prepare PR if you like.

**Comment by mobileoverlord** [comment]
Sure that would be great :)
