### ISSUE TITLE
Error when creating mssql db with ecto

### ISSUE THREAD

**Issue by SerhiiKozachenko** [livehelpnow/tds_ecto#32]
I am on Windows 10 Pro 64 bit

I just started Elixir Phoenix new web app with:

```
mix phoenix.new phoenix_sample --database mssql
```

It generated config/dev.exs file with db configuration, I have modified to match my current ms sql server:

```
config :phoenix_sample, PhoenixSample.Repo,
  adapter: Tds.Ecto,
  username: "dev",
  password: "dev",
  database: "phoenix_sample_db",
  hostname: "localhost",
  pool_size: 10
```

I am able to login into ssms as `dev` user and connect to `phoenix_sample_db` database

But when I run: `mix ecto.create`

I always error out:

```
$ mix ecto.create
** (EXIT from #PID<0.46.0>) %Tds.Error{message: "tcp connect: econnrefused", mssql: nil}

23:25:20.208 [error] GenServer #PID<0.149.0> terminating
** (stop) %Tds.Error{message: "tcp connect: econnrefused", mssql: nil}
Last message: {:connect, [port: 1433, hostname: "SERG-MAC", database: "master",
otp_app: :phoenix_sample, repo: PhoenixSample.Repo, adapter: Tds.Ecto, username: "dev", password: "dev"]}
State: %{attn_timer: nil, env: %{trans: <<0>>}, ireq: nil, itcp: nil, opts: [port: 1433, hostname: "SERG-MAC", database: "master", otp_app: :phoenix_sample, repo: PhoenixSample.Repo, adapter: Tds.Ecto, username: "dev", password: "dev"], pak_data: "", pak_header: "", queue: {[{{:connect, [port: 1433, hostname: "localhost", database: "master", otp_app: :phoenix_sample, repo: PhoenixSample.Repo, adapter: Tds.Ecto, username: "dev", password: "dev"]}, {#PID<0.46.0>, #Reference<0.0.2.1881>}, #Reference<0.0.2.1882>}], []}, sock: nil, state: :ready, statement: nil, tail: "", usock: nil}
```

Why it's not working and why `ecto` trying to connect to `master` db?

I have tried turn off firewall but it doesn't help

**Comment by nubunto** [comment]
+1

Any workarounds?

**Comment by nubunto** [comment]
In my fork, I have this problem (parcially) solved: https://github.com/nubunto/tds_ecto

Still, I'm getting timeouts on connecting to MSSQL.

**Comment by SerhiiKozachenko** [comment]
I have solved it by enabling TCP/IP protocol on my mssql server instance.

**Comment by nubunto** [comment]
@Grievoushead are you using SQL Express? In my SQL Express instance, even after enabling the TCP/IP Protocol on it, it doesn't work. But, on a SQL Server, it works with no problems.
