### ISSUE TITLE
decode_tokens failing

### ISSUE THREAD

**Issue by pinx** [livehelpnow/tds_ecto#39]
When running ecto.migrate against a SQL 2008R2 db, the message returned can´t be parsed. Maybe a codepage or encoding issue?
It says "no function clause matchiing": Tds.Tokens.decode_token(<<0, 0, 0, 0, 0, 0, 0, 0, 121, 246, 31, 0, 0, 172, 0, 0, 7, 64, 0, 104, 0, 97, 0, 110, 0, 100, 0, 108, 0, 101, 0, 1, 0, 0, 0, 0, 0, 0, 38, 4, 4, 2, 0, 0, 0, 254, 0, 0, 224, 0, ...>>
I am connecting with SQL auth, the user has sysadmin rights.

**Comment by mjaric** [comment]
It is hard to tell without giving concrete case of query, and since this is related to ecto 1.X I will close the issue. Anyhow, if you are still getting same error with latest version please reopen this ticket.

Thanks
