### ISSUE TITLE
Weird syntax for schema other than dbo

### ISSUE THREAD

**Issue by burmajam** [livehelpnow/tds_ecto#4]
Hi, I've found out that in order to map model to table out of dbo schema, one needs to write as follows:

```
schema "users].[contacts" do
  #...
end
```

Is it by design or is it a bug?

**Comment by mobileoverlord** [comment]
All the table names are quoted in `[tablename]` in the connection. We could probably do a split on `.` then join it back quoted.

**Comment by mobileoverlord** [comment]
Can you try removing your `].[` running on master?

**Comment by burmajam** [comment]
sure ... give me few minutes

**Comment by burmajam** [comment]
Yes ... works as expected now. Thanks!

**Comment by mobileoverlord** [comment]
Sure thing, I'll push an update to hex.

**Comment by burmajam** [comment]
Perfect! Thanks again.
