### ISSUE TITLE
Unable to set encoding on the repo

### ISSUE THREAD

**Issue by kh0r** [livehelpnow/tds_ecto#54]
According to your documentation it's possible to set the encoding on the repo: https://github.com/livehelpnow/tds_ecto/blob/74e020f04520567b4171cc7c3c03a25ebafe99b4/lib/tds_ecto.ex#L49

This doesn't seem to work for me. No matter what I write as value, I get wrongly encoded data.

This should imho be the correct config:
```elixir
config :ciq, Ciq.SourceRepo,
  adapter: Tds.Ecto,
  encoding: "latin-1",
  ...
```

e.g. the string `Curaçao` gets read as `<<67, 117, 114, 97, 231, 97, 111>>` but should be read as `<<67, 117, 114, 97, 195, 167, 97, 111>>`

**Comment by mjaric** [comment]
Hi @kh0r 

Sorry for delayed response. I'm not sure if that worked so far, it is UTF-8 always, I will check old 1.X version to see if there was any functions which did any other encoding. I know that current codebase do not have anything which used that configuration flag, it simply converts bitstring to ucs-2 binary. If I'm not wrong nvarchar should keep you safe here, so if you are using nvarchar columns you should get correct string back to the client app. 


Finally, could you please let me know if example you showed in issue, is that something you tried to store in varchar column?
