### ISSUE TITLE
paginated selects holds onto handles, crashes

### ISSUE THREAD

**Issue by jedeleh** [livehelpnow/tds_ecto#55]
So I've got a SQL Server database I'm loading records out of in a paginated fashion:

```
defmodule TestRepo do
  defp get(offset) do
    events = MyRepo.all(
     from t in MyEvent,
        where: t.completed == 0,
        order_by: [desc: :occurred_at],
        limit: 50,
        offset: ^offset
    )
  end
end
```

NOTE: I'm running this from `iex -S mix`.

There are 24 million rows in the table I'm selecting from. 

What I'm seeing is after around 12700 rows I get this error:

> ** (Tds.Error) 1 (8179): Could not find prepared statement with handle 0.
>     (ecto) lib/ecto/adapters/sql.ex:440: Ecto.Adapters.SQL.execute_or_reset/7
>     (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
>     (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
>     (event_bridge) lib/event_bridge_runner.ex:24: EventBridgeRunner.get/2
>     (event_bridge) lib/event_bridge_runner.ex:18: anonymous fn/2 in EventBridgeRunner.bare_bones/0
>     (elixir) lib/enum.ex:1841: Enum.reduce_range_inc/4
>     (event_bridge) lib/event_bridge_runner.ex:17: EventBridgeRunner.bare_bones/0

At the same time, the DBA that is helping me with this says that he's seeing the query being prepared each time it's run (rather than preparing the query once and then executing it with different parameters each time).  By "preparing" I mean he sees this on his side of things when he traces:

> declare @p1 int
> set @p1=209
> exec sp_prepare @handle=@p1 output,@params=N'@2 bigint, @1 bigint',@stmt=N'SELECT t0.[id], t0.[access_dates], t0.[action], t0.[athlete_email], t0.[athlete_first_name], t0.[athlete_id], t0.[athlete_last_name], t0.[athlete_sport_id], t0.[coach_email], t0.[coach_first_name], t0.[coach_id], t0.[coach_last_name], t0.[coach_position], t0.[coach_sport_id], t0.[college_name], t0.[completed], t0.[deleted], t0.[deleted_at], t0.[detail], t0.[failure_reason], t0.[ipeds_id], t0.[occurred_at], t0.[partner_name], t0.[pass_uuid], t0.[source_application] FROM [tbl_temp_jds_csv_events_2] AS t0 WHERE (t0.[completed] = 0) ORDER BY t0.[occurred_at] DESC OFFSET @2 ROW FETCH NEXT @1 ROWS ONLY'
> select @p1

When I run this same code against a postgres database using the default adapter provided by Ecto, I do not get the error. This leads me to believe that it is related to tds_ecto so I'm posting this here. 

It's possible there's some configuration I need to do for this adapter that I'm unaware of. I'm at the point where I can't actually page through my dataset in sql server.

**Comment by jedeleh** [comment]
Note, I have reproduced this issue by running a script rather than executing the code from within `iex -S mix`

**Comment by mjaric** [comment]
I'm not sure which version of tds_ecto you are using, but anyways try to do `mix deps.update tds` we recently fixed issue with error you mentioned, but it was with 255 handle. I see you passed that number, so this could be issue with next range in integer size. 

Could you please check if you have latest tds, run command I mentioned and let me know if it fails again

Thank you

**Comment by mjaric** [comment]
actually, you mentioned 12700 records with should be exactly 254 handles created in database. I think you should be ok with `mix deps.update tds` (it is TDS which suffers from this bug)

**Comment by jedeleh** [comment]
Bingo. I'm closing this (with my heartfelt thanks because I've been struggling with this for 2 days now and the business person is looking at me askance recently), and will only revisit it if I hit a higher issue with this.
