### ISSUE TITLE
Sluggish?

### ISSUE THREAD

**Issue by cpursley** [livehelpnow/tds_ecto#67]
I swapped out the [mssql_ecto](https://github.com/findmypast-oss/mssql_ecto) adapter for tds_ecto mainly due to its support of nvarchar(max) types. That works great, thanks for creating this library!

However, queries are very sluggish ~ slower than before by approximately a factor of 3. Is this a known issue, or perhaps I'm not configuring tds_ecto correctly?

My deps look like this:

```
  defp deps do
    [
      {:phoenix, "~> 1.3.4"},
      {:phoenix_pubsub, "~> 1.1.0"},
      {:phoenix_ecto, "~> 3.4.0"},
      {:gettext, "~> 0.16.0"},
      {:cowboy, "~> 1.0"},
      {:absinthe, "~> 1.4.13"},
      {:absinthe_ecto, "~> 0.1.0"},
      {:absinthe_plug, "~> 1.4.4"},
      {:absinthe_phoenix, "~> 1.4.3"},
      {:dataloader, "<= 1.0.4"},
      {:tds_ecto, "~> 2.2.1"},
      {:faker, "~> 0.10.0"},
      {:timex, "~> 3.4.1"},
      {:distillery, "~> 2.0.10", runtime: false},
      {:corsica, "~> 1.1.2"}
    ]
  end
```

While my config looks like this:

```
config :my_app, MyApp.Repo,
  database: <db_name>,
  username: <server_name>,
  password: <server_password>,
  hostname: <server_address>,
  instance_name: "MSSQLSERVER",
  pool_size: 40
```

**Comment by mjaric** [comment]
Could you please check what ecto logger reports after query execution. It should tell how long it was in queue, query (waiting result) and then decoding. The last (decoding) is what is possible to optimize in this library. Query, it is how performant SQL server is, and queue tells if you need wider pool but it should be last resort to resolve bottlenecks.

**Comment by cpursley** [comment]
Thanks for the quick reply @mjaric 

These are the results from ecto logger. However, I did not see _queue_ in the logs. Is this something that requires configuration?

```
...
[debug] QUERY OK source="vwSomeDbView" db=2148.6ms decode=0.1ms
...
[debug] QUERY OK source="tblSomeDbTable" db=1279.1ms decode=2.2ms
```

Also, I ran the same queries from the logger directly in the Db with much faster results (246ms and 281ms, respectively). What else can I share to help profile?

**Comment by mjaric** [comment]
I presume that your pool is bigger than what you app usually needs, and that is ok. If you don't see something like `queue=1.3ms`, then query didn't wait in queue and was executed immediately. 

One note here. If you see difference between `mssq_ecto` and `tds_ecto` one reason could be if you trying to compare `varchar` field with `nvarchar` parameter since in `tds_ecto`, if you don't say what db_type string parameter should be, `tds_ecto` (and `tds`) will threat it as `nvarchar` and that could increase reads in sql execution plans. 

To ensure string parameter is sent as `:varchar` use `Tds.VarChar` for the column type in schema, then use ecto tagging to tag parameter as varchar, something like below

```elixir
import Ecto.Query
# ...
q = from s in SomeTable,
       where: s.title == type(^title, :varchar)
# ...or
q = from s in SomeTable,
       where: s.title == type(^title, s.title) # use same type as column has 
```

And finally, since for some reason Microsoft has different way of keeping UUID bytes, please use `Tds.UUID` and not `Ecto.UUID` or you will face some weirdness :) 

### EDIT

```elixir
import Ecto.Query
# ...
q = from s in SomeTable,
       where: s.title == type(^title, Tds.VasrChar)
# ...or
q = from s in SomeTable,
       where: s.title == type(^title, s.title) # use same type as column has 
```

**Comment by cpursley** [comment]
Hum, I went ahead and converted the remaining `:varchars` to `Tds.VarChar` as well as specifying the relevant type via ecto tagging (it did not like the :varchar, so I had to use the s.title approach ~ which works).

The error I got when trying :varchar looks something like this:

```
Request: POST /graphiql
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function :varchar.cast/1 is undefined (module :varchar is not available)
        :varchar.cast(true)
        (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/repo/queryable.ex:124: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
        (ecto) lib/ecto/repo/queryable.ex:70: Ecto.Repo.Queryable.one/4
        (my_app) lib/my_app/activity.ex:78: MyApp.Activity.latest_id/1
        (my_app) lib/my_app_web/resolvers/activity_resolver.ex:7: MyApp.ActivityResolver.get_activity/3
        (absinthe) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:209: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:168: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:72: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:53: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
        (absinthe) lib/absinthe/pipeline.ex:274: Absinthe.Pipeline.run_phase/3
        (absinthe_plug) lib/absinthe/plug.ex:414: Absinthe.Plug.run_query/4
        (absinthe_plug) lib/absinthe/plug.ex:240: Absinthe.Plug.call/2
        (phoenix) lib/phoenix/router/route.ex:147: Phoenix.Router.Route.forward/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (my_app) lib/my_app_web/endpoint.ex:1: MyAppWeb.Endpoint.plug_builder_call/2
        (my_app) lib/my_app_web/endpoint.ex:1: MyAppWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /app/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by mjaric** [comment]
My bad, fist option should be `type(^title, Tds.VarChar)`

**Comment by cpursley** [comment]
Opps, that should have occurred to me as :varchar is not a thing in Elixir/ecto :)

**Comment by cpursley** [comment]
Is there anything else I can look into and report back with to help profile this issue?

**Comment by mjaric** [comment]
Sorry for delayed response.
I think it has something to do with different execution plans due differences in how wuery is executed. From s l management studio whole query is sent as unicode string. Tds uses tds package format which should have advantages but only if parameter types are correctly set. So what you need to do is to compare execution plans for sql handles that are created for tds and ssms and queries captured by sql profiler. Tds makes two calls one is sp_prepare and second is sp_execute handle. So in first one you will see sql query as with parameter definitions and second is execution with parameter values. Ssms will probaby send only one call and you should see complete query there with parameters embedded into query. From profiler you will find column called sql-handle as hex number. Use it to discover execution plan from sys.dm_exec_query_plan

Once you open both plans in ssms first check if there is any warnings and then if not compare plan to find out what makes tds call slower

**Comment by mjaric** [comment]
Hi @cpursley, any success with this?

**Comment by cpursley** [comment]
Hi @mjaric ~ I haven't had a chance to look into it yet. Perhaps later today or next week.

My biggest observation is that everything performs fine (really fast) locally where I'm running SQL Server in a Docker container.

However, the issue is only when I either connect to our remote server (Microsoft SQL Server 2016) via my local machine or staging environment (which is in the same datacenter as SQL Server).

I'll report back when I have more to share, thanks for following up.

**Comment by mjaric** [comment]
Yes, latency cold kill performance since tpc will lost about 50ms in best case for each 1.4k bytes. Depending on your result it could pile up quickly to half second of idle time where kernel waits for next package. I don’t think you can resolve that without bying expensive   link :)

**Comment by cpursley** [comment]
Hi @mjaric ~ I have some time to look into this again.

Do you think that the new Execution mode feature from the tds library might help: https://github.com/livehelpnow/tds/commit/e06c40a55f591ef6f3163aca30a34d8890a0f7aa

How could we use it in this library?

Perhaps related:
- https://groups.google.com/forum/#!topic/querydsl/ZGQi4M59SNM
- https://www.brentozar.com/archive/2018/03/sp_prepare-isnt-good-sp_executesql-performance/

**Comment by mjaric** [comment]
Commit you mentioned only can help if, and only if, your query should not use density estimates. And it is not silver bullet!

Everything you need to know about sluggish behavior can be seen in sql profiler while tracing queies (number of reads, etc.) and dm_* views. I presume cloud sql server has more data in tables than your local database, so issue is probably easier to catch there instead on local sql server.

I could help interpreting traces or exec plans. If you can share, please contact me on email. But be patient if I don't respond instantly since I have to do it after my work.

**Comment by naag** [comment]
@cpursley If you'd still like to use the new `execution_mode` setting, just edit your `config/config.exs` and add `execution_mode: :executesql` to your repo config, for example:

```
config :my_app, MyApp.Repo,
  adapter: Tds.Ecto,
  username: "username",
  password: "password",
  database: "database",
  hostname: "1.2.3.4",
  execution_mode: :executesql
```
