### ISSUE TITLE
Limit and Offset in MS SQL 2012

### ISSUE THREAD

**Issue by alexjp** [livehelpnow/tds_ecto#7]
Hi,

I am on SQL 2012 server, and with success on using offset in direct sql.

But with tds_ecto, am trying to do the following query:

```
    query = from i in Artigo,
      select: i,
      order_by: i.Artigo,
      offset: 1

Repo.all(query)
```

With the result of : 
[error] #PID<0.2152.0> running Crmonline.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /api/artigos?skip=10
*\* (exit) an exception was raised:
    *\* (Tds.Error) 1 (102): Incorrect syntax near '1'.

Am I missing something ?

**Comment by mobileoverlord** [comment]
This may have been fixed in a recent update. Could you try this again and if it is still broken can you run in debug and provide the output SQL that is being run?

**Comment by alexjp** [comment]
Sure, i will report back !

**Comment by alexjp** [comment]
report: 

```
[debug] SELECT c0.[id], c0.[name], c0.[formation] FROM [companies] AS c0 ORDER BY c0.[name] OFFSET 1 [] ERROR query=361.5ms
[info] Sent 500 in 418ms
[error] #PID<0.507.0> running Crmonline.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /api/companies
** (exit) an exception was raised:
    ** (Tds.Error) 1 (102): Incorrect syntax near 'OFFSET'.
        (ecto) lib/ecto/adapters/sql.ex:209: Ecto.Adapters.SQL.log_and_check/7
        (ecto) lib/ecto/adapters/sql.ex:429: Ecto.Adapters.SQL.all/6
        (ecto) lib/ecto/repo/queryable.ex:22: Ecto.Repo.Queryable.all/4
        (crmonline) web/controllers/company_controller.ex:15: Crmonline.CompanyController.index/2
        (crmonline) web/controllers/company_controller.ex:1: Crmonline.CompanyController.phoenix_controller_pipeline/2
        (crmonline) lib/phoenix/router.ex:297: Crmonline.Router.dispatch/2
        (crmonline) lib/phoenix/router.ex:2: Crmonline.Router.call/2
        (crmonline) lib/crmonline/endpoint.ex:1: Crmonline.Endpoint.phoenix_endpoint_pipeline/1
[error] backend port not found: :inotifywait
```

mix.lock 
%{"cowboy": {:hex, :cowboy, "1.0.0"},
  "cowlib": {:hex, :cowlib, "1.0.1"},
  "decimal": {:hex, :decimal, "1.1.0"},
  "ecto": {:hex, :ecto, "0.12.1"},
  "fs": {:hex, :fs, "0.9.2"},
  "hackney": {:hex, :hackney, "1.1.0"},
  "httpoison": {:hex, :httpoison, "0.7.0"},
  "idna": {:hex, :idna, "1.0.2"},
  "jsonapi": {:git, "git://github.com/jeregrine/jsonapi.git", "9877baf7f1c163640f5b44d2bcbe7a70c0dfb0e2", []},
  "phoenix": {:hex, :phoenix, "0.13.1"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "0.5.0"},
  "phoenix_html": {:hex, :phoenix_html, "1.2.1"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "0.4.1"},
  "plug": {:hex, :plug, "0.13.0"},
  "plug_cors": {:hex, :plug_cors, "0.7.3"},
  "poison": {:hex, :poison, "1.4.0"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.8.4"},
  "ranch": {:hex, :ranch, "1.0.0"},
  "ssl_verify_hostname": {:hex, :ssl_verify_hostname, "1.0.5"},
  "tds": {:hex, :tds, "0.2.8"},
  "tds_ecto": {:git, "git://github.com/livehelpnow/tds_ecto.git", "3508d28a02d711bc9f79535fd2f1354a59850449", []},
  "timex": {:hex, :timex, "0.15.0"},
  "tzdata": {:hex, :tzdata, "0.1.6"}}

**Comment by mobileoverlord** [comment]
Thanks Alex, I think I see the problem. Looks like SQL syntax for OFFSET should be OFFSET x ROWS. I'll get this patched up and let you know when to test again.

**Comment by mobileoverlord** [comment]
This has been fixed in master, can you test

**Comment by mobileoverlord** [comment]
I am going to close this out. Let me know if you are still experiencing problems.
