### ISSUE TITLE
Update the db_connection dependency

### ISSUE THREAD

**Issue by renews** [livehelpnow/tds_ecto#70]
As a new project with latest ecto_sql use db_connection 2.0 but tds requires 1.1

`Failed to use "db_connection" (version 2.0.3) because
  ecto_sql (version 3.0.4) requires ~> 2.0
  postgrex (version 0.14.1) requires ~> 2.0
  tds (versions 1.1.0 to 1.1.6) requires ~> 1.1
  mix.lock specifies 2.0.3`

**Comment by mjaric** [comment]
Hi @renews 

This repository is pre Ecto 3.0 and will not change anymore. The reason is already explained [here](https://github.com/livehelpnow/tds_ecto/issues/69)
