### ISSUE TITLE
Performance of float fields

### ISSUE THREAD

**Issue by alexjp** [livehelpnow/tds_ecto#8]
Hi,

I am using tds_ecto against a sql server 2008r2, with a table that has 6 float columns.

When querying the table ( which has more than 31000 ) registies, without the float columns, its "fast" ( only takes 3 seconds ). When including the float columns in the model, it takes.. alot of time. The most i got was waiting 5 minutes and then timeout stopped it.

Thanks!

**Comment by alexjp** [comment]
Update, for example, selecting a table with 6 floats and 33000 rows, took :

[info] Sent 200 in 466251ms

**Comment by mobileoverlord** [comment]
Sorry for the delay, I'll be taking a look at this today.

**Comment by ro31337** [comment]
@alexjp can you publish source code so I can reproduce that? Thanks

**Comment by alexjp** [comment]
unfortunately no, not the original code that I was using.

I will do a ms sql script to create some tables and views, and then elixir code to use them and trigger the slow performance.

is that ok ?

**Comment by alexjp** [comment]
@ro31337 can you work with something like this: https://gist.github.com/alexjp/292284778d1032891ca8 ?

This is a legacy proprietary app, closed source. I changed most of the column names and other things, don't want to get into trouble.

With a table like that, with that many floats, and with 10000 records, tds_ecto becomes really slow !
With the same number of records, but not using the floats, its fast!

**Comment by ro31337** [comment]
@alexjp OK, I'll take a look at that

**Comment by mobileoverlord** [comment]
I'm curious if this is general slowness in how Elixir handles floats. The parsing for this happens here
https://github.com/livehelpnow/tds/blob/master/lib/tds/types.ex#L341-L346

This is just using the standard bitstring sugar for decoding the float value.

**Comment by ro31337** [comment]
@alexjp btw, what if you'll replace all of the float fields with money type, like that:

```
field :ffield00plus, :float
```

with

```
field :ffield00plus, :money
```

?

**Comment by alexjp** [comment]
@ro31337 there is a type 

```
:money
```

?

Will try tomorrow at work and let you know !

**Comment by alexjp** [comment]
@mobileoverlord  could i  send you a personal email or meet in irc so that i could send you the debug of the app ( it has the correct sql and etc, so would like to keep it private ) ?
