### ISSUE TITLE
Error when making query

### ISSUE THREAD

**Issue by alexjp** [livehelpnow/tds_ecto#9]
Hi,

Upon doing a query to a MSSQL 2008R2, most of the times it returns an error:

```
** (exit) exited in: GenServer.call(#PID<0.386.0>, {:query, "SELECT a0.[artigo], a0.[descricao], a0.[fornecedor], a0.[familia], a0.[subfamilia], a0.[unidadeBase], a0.[unidadeVenda] FROM [artigo] AS a0  ORDER BY a0.[artigo]", [], [timeout: 1500000]}, 1500000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: <<4, 0, 16, 0>>
            (tds) lib/tds/connection.ex:278: Tds.Connection.new_data/2
            (tds) lib/tds/connection.ex:221: Tds.Connection.handle_info/2
            (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
            (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

Upon retrying again, it works. ( its more or less miss and retry and it works ). I dont have to restart the server or change code, just try again.

Thanks

**Comment by mobileoverlord** [comment]
This should be resolved in master, could you check?

**Comment by mobileoverlord** [comment]
Sorry I should clarify, this has been fixed in tds, the underlying driver on its master. Can you override tds to pull from livehelpnow/tds and try

**Comment by alexjp** [comment]
Sure, I will try and report back in the next 24 hours.

Thanks!

**Comment by alexjp** [comment]
Seems to be fixed, i think i can close it.

I was using tds version 2.8, should include the fix. Connection seem stable upon lots of refreshs.
